#!/usr/bin/php
<?php

/**
 * CLI-based script accepting input conditions file on STDIN, a list of command
 * line arguments and providing generated class on STDOUT. Errors output via
 * STDERR.
 */

require __DIR__ . '/../vendor/autoload.php';

call_user_func(function() use ($argv){
    // read ruleset file from STDIN
    $input_json = file_get_contents('php://stdin');
    
    // check file is not empty
    if (empty(trim($input_json))) {
        die("Usage: ".basename($argv[0])." <ruleset.json >RuleSet.php\nSee README.md for ruleset file format\n");
    }

    // convert from json to native array
    $input_array = json_decode($input_json, true);
    if (isset($input_array)) {
        echo (new Recif\Platform\Php\RuleConvertor($input_array))->convert();
    } else {
        die('Cannot process input: ' . json_last_error_msg() . "\n");
    }
});
